### ISSUE TITLE
Can't watch video from https://www.discoveryplus.com/ because of DRM problem

### ISSUE THREAD

**Issue by realmax44** [ferdium/ferdium-server#77] opened 2023-09-23 08:00 UTC
Hi. I've tried to add https://www.discoveryplus.com/ as a custom website, but it doesn't work for me. There's always an error when trying to watch a video. It seems to be a DRM problem in Ferdium. This happens on the earlier and the latest nightly version of Ferdium on macOS.

**Comment by victorbnl** [comment] 2023-09-23 10:38
This is because Widevine CDM is missing in Ferdium, which prevents DRM-protected content from playing. Closing as a duplicate of https://github.com/ferdium/ferdium-app/issues/687.

**Closed by victorbnl** 2023-09-23 10:38 UTC
