### ISSUE TITLE
Ferdium-Server Not Support arms server (ubuntu) - Docker issue

### ISSUE THREAD

**Issue by mzayn** [ferdium/ferdium-server#48] opened 2022-07-25 04:19 UTC
hi, 

i got this error when deploy using Docker

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
9bb2c072c942c03062f8136f33ef0abfc22c7526382
```

hope can support arm64/linux (ubuntu) server for ferdium

Thanks

**Comment by SpecialAro** [comment] 2022-07-25 07:35
Duplicate of #45

**Closed** 2022-07-25 07:36 UTC
